name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3

      - name: Build and run Docker container
        run: |
          docker build -t bitcoin-price-app:latest .
          docker run -d --name bitcoin-app-container bitcoin-price-app

      - name: Wait for container to start
        run: sleep 5

      - name: Run tests
        run: docker exec bitcoin-app-container vendor/bin/phpunit