name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: bitcoin_test
          MYSQL_USER: root
          MYSQL_PASSWORD: secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker build -t bitcoin-price-app:latest .
          docker run -d --name bitcoin-app-container bitcoin-price-app

      - name: Wait for container to start
        run: sleep 5

      - name: Run migrations
        run: docker exec -e APP_ENV=testing bitcoin-app-container php artisan migrate --database=bitcoin_test

      - name: Run tests
        run: docker exec -e APP_ENV=testing bitcoin-app-container vendor/bin/phpunit
