name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker build -t bitcoin-price-app:latest .
          docker run -d --name bitcoin-app-container bitcoin-price-app

      - name: Wait for container to start
        run: sleep 5

      - name: Configure MySQL for tests
        run: |
          cp .env.testing .env
          sed -i 's/DB_HOST=.*/DB_HOST=mysql/g' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=myapp_test/g' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=myuser/g' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=mypassword/g' .env


      - name: Run tests
        run: docker exec -e APP_ENV=testing bitcoin-app-container vendor/bin/phpunit
